apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaa.fullname" . }}-keys
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Values.metadata.partOf }}
    app.kubernetes.io/component: {{ .Values.metadata.component }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "kaa.chart" . }}
type: Opaque
data:
  bootstrap-private.key: {{ .Values.kaa.servers.bootstrap.keys.privateB64 }}
  bootstrap-public.key: {{ .Values.kaa.servers.bootstrap.keys.publicB64 }}
  operations-private.key: {{ .Values.kaa.servers.operations.keys.privateB64 }}
  operations-public.key: {{ .Values.kaa.servers.operations.keys.publicB64 }}