apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaa.fullname" . }}-servers
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    helm.sh/chart: {{ include "kaa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: {{ .Values.serviceServers.type }}
  ports:
    - port: {{ .Values.kaa.config.bootstrapHttpTransport.bindPort }}
      targetPort: bootstrap-http
      protocol: TCP
      name: bootstrap-http
      {{ if (and (eq .Values.serviceServers.type "NodePort") (not (empty .Values.serviceServers.bootstrapHttpNodePort))) }}
      nodePort: {{.Values.serviceServers.bootstrapHttpNodePort}}
      {{ end }}
    - port: {{ .Values.kaa.config.bootstrapTcpTransport.bindPort }}
      targetPort: bootstrap-tcp
      protocol: TCP
      name: bootstrap-tcp
      {{ if (and (eq .Values.serviceServers.type "NodePort") (not (empty .Values.serviceServers.bootstrapTcpNodePort))) }}
      nodePort: {{.Values.serviceServers.bootstrapTcpNodePort}}
      {{ end }}
    - port: {{ .Values.kaa.config.operationsHttpTransport.bindPort }}
      targetPort: operations-http
      protocol: TCP
      name: operations-http
      {{ if (and (eq .Values.serviceServers.type "NodePort") (not (empty .Values.serviceServers.operationsHttpNodePort))) }}
      nodePort: {{.Values.serviceServers.operationsHttpNodePort}}
      {{ end }}
    - port: {{ .Values.kaa.config.operationsTcpTransport.bindPort }}
      targetPort: operations-tcp
      protocol: TCP
      name: operations-tcp
      {{ if (and (eq .Values.serviceServers.type "NodePort") (not (empty .Values.serviceServers.operationsTcpNodePort))) }}
      nodePort: {{.Values.serviceServers.operationsTcpNodePort}}
      {{ end }}



  selector:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}