apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaa.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    helm.sh/chart: {{ include "kaa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "kaa.kaaPort" . }}
      targetPort: admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}