apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kaa.fullname" . }}-aws
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "kaa.chart" . }}
type: Opaque
data:
  aws-access-key-id: "{{ .Values.aws.accessKey | b64enc }}"
  aws-secret-access-key: "{{ .Values.aws.secretKey | b64enc }}"
