---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kaa.fullname" . }}-kaa-config-updater
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    helm.sh/chart: {{ include "kaa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kaa.fullname" . }}-kaa-config-updater
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    helm.sh/chart: {{ include "kaa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["update", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "kaa.fullname" . }}-kaa-config-updater
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    helm.sh/chart: {{ include "kaa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kaa.fullname" . }}-kaa-config-updater
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kaa.fullname" . }}-kaa-config-updater
