apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaa.fullname" . }}-thrift
  labels:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    helm.sh/chart: {{ include "kaa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.serviceThrift.type }}
  ports:
    - port: {{ .Values.serviceThrift.port }}
      targetPort: thrift
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kaa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}